_target_: src.lightning.lightning_modules.semi_supervised.GMM_based.SelfSemiOneGMM
_recursive_: False

backbone1:
  _target_: src.modeling.registry.create_model
  model_name: finetune_linear_all_centers
  seed: ${seed}
  split_seed: ${split_seed}

semi_sup: False
temperature: 0.1
beta_alpha: 0.75
GMM_cycle: 3