
# @package _global_
_recursive_: false # recursive instantiation while using hydra.util.instantiate. 
#https://hydra.cc/docs/advanced/instantiate_objects/overview/#recursive-instantiation 

defaults:
  - /logger: wandb # / "slash" is for recognizing logger folder in previous folder 
  
  # - /datamodule@config.datamodule: sl_datamodule
  # - /callbacks@config.callbacks: finetune.yaml
  # - /trainer@config.trainer: default.yaml
  # - /model@config.model: supervised