
# TODO this is not tested

defaults:
  - patch_datamodule_base
  - transform@patch_transform_train: no_augs
  - transform@patch_transform_eval: no_augs
  - splits: uva600
  - _self_ 

_target_: src.lightning.datamodules.exact_datamodule.PatchDataModuleForSemiSupervisedLearning

patch_view_config: 
  needle_region_only: false
  prostate_region_only: true
  patch_strides: [3, 3]

splits: 
  train_val_ratio: 0.2
  cohort_specifier: [UVA600, CRCEO428]
  undersample_benign_eval: true
  undersample_benign_train: true
  