_target_: src.lightning.lightning_modules.supervised.patch_coteaching_model.SupervisedCoteachingModel
_recursive_: False

model1: 
  _target_: src.modeling.registry.registry.create_model
  model_name: resnet10

model2: 
  _target_: src.modeling.registry.registry.create_model
  model_name: resnet10
  
loss_name: edl_loss
semi_sup: False

final_remember_rate: 0.6
final_remember_rate_epoch_frac: 0.1

batch_size: ${driver.config.datamodule.loader_config.batch_size}
epochs: ${driver.config.trainer.max_epochs}
