_target_: src.modeling.registry.ts_model_registry.create_model
model_name: nbeats
input_chunk_length: 24
output_chunk_length: 12
random_state: ${seed} # randomness in weight initializations
batch_size: ${batch_size}
# optimizer
optimizer_cls: torch.optim.Adam
optimizer_kwargs: 
  lr: 0.0001
  weight_decay: 0
  amsgrad: false
# lr_scheduler_cls: torch.optim.lr_scheduler.LambdaLR
# lr_scheduler_kwargs:
#   lr_lambda: 
#     _target_: src.modeling.registry.optimizer_scheduler.cosine_annealing_with_linear_warmup
#     T_max: ${epochs}
#     eta_min: 0.0
#     eta_max: ${model.optimizer_kwargs.lr}
#     warmup_epochs: 5
#     lr: ${model.optimizer_kwargs.lr}

