# _recursive_: true
_target_: src.modeling.registry.ts_model_registry.create_model
model_name: nbeats
input_chunk_length: 24
output_chunk_length: 12
random_state: ${seed} # randomness in weight initializations
batch_size: ${batch_size}

# loss
loss_fn: 
  _target_: src.modeling.registry.loss_registry.TorchLosses
  loss_name: mse

# optimizer
optimizer_cls: 
  _target_: hydra.utils.get_method # passes optim.Adam to the optimizer_cls instead of an object of this optimizer
  path: torch.optim.Adam
optimizer_kwargs: 
  lr: 0.001
  weight_decay: 0
  amsgrad: false

# scheduler
lr_scheduler_cls:
  _target_: hydra.utils.get_class
  path: src.modeling.registry.optimizer_scheduler.LambdaLRWrapper
lr_scheduler_kwargs:
  T_max: ${epochs}
  eta_min: 0.0
  eta_max: ${model.optimizer_kwargs.lr}
  warmup_epochs: 5
  wandb_log: ${logger} # TODO: this might make offline loading problematic

