_target_: darts.models.forecasting.nbeats.NBEATSModel
input_chunk_length: 24
output_chunk_length: 12
random_state: ${seed}
batch_size: ${batch_size}

# save_checkpoints=False,
# nr_epochs_val_period=1,
# model_name=None,
# pl_trainer_kwargs=pl_trainer_additional_kwargs