_target_: src.driver.pytorch_lightning_experiment.FinetuningDriver
_recursive_: false

defaults:
  - /datamodule@config.datamodule: sl_datamodule
  - /model@config.model: finetuner
  - /callbacks@config.callbacks: finetune
  - /logger@config.logger: wandb # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - /trainer@config.trainer: default

config: 

  seed: ${seed}

  model:
    backbone:
      _target_: src.modeling.registry.create_model
      model_name: vicreg_resnet_10_crops_split_seed_2