# @package _global_
# defaults:
#   - _self_
#   - override hydra/sweeper: optuna

hydra:
  run:
    dir: ${workdir_lookup:${name},${resume_id}}    
  #  dir: logs/experiments/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  #  subdir: .